from arar.materials.rhythm import composite_handler_one, rhythm_handler_one

rhythm_material_list = [
    rhythm_handler_one,
    rhythm_handler_one,
    rhythm_handler_one,
    rhythm_handler_one,
    rhythm_handler_one,
    rhythm_handler_one,
    rhythm_handler_one,
    rhythm_handler_one,
    rhythm_handler_one,
    rhythm_handler_one,
    rhythm_handler_one,
    composite_handler_one,
    composite_handler_one,
    composite_handler_one,
    composite_handler_one,
    composite_handler_one,
    composite_handler_one,
    composite_handler_one,
    composite_handler_one,
    composite_handler_one,
    composite_handler_one,
    composite_handler_one,
    composite_handler_one,
    composite_handler_one,
    composite_handler_one,
    composite_handler_one,
    composite_handler_one,
    composite_handler_one,
    composite_handler_one,
    composite_handler_one,
    composite_handler_one,
]
