import evans

pitch_handler_one = evans.PitchHandler(
    pitch_list=[15],
    forget=False,
)

pitch_handler_two = evans.PitchHandler(
    pitch_list=[3],
    forget=False,
)

###
###

flute_pitch_handler_one = evans.PitchHandler(
    pitch_list=[
        "f''",
        "f''",
        "f''",
        "f''",
        "e''",
        "e''",
        "cs''",
        "cs''",
        "c'''",
        "c'''",
        "c'''",
        "c'''",
        "c'''",
        "c'''",
        "fs''",
        "fs''",
        "cs''",
        "cs''",
        "g'",
        "g'",
        "a'",
        "a'",
        "a'",
        "a'",
        "fqs''",
        "fqs''",
        "fs''",
        "fs''",
        "ftqs''",
        "ftqs''",
        "f''",
        "f''",
    ],
    forget=False,
)

guitar_pitch_handler_one = evans.PitchHandler(
    pitch_list=[
        [
            "e",
            "c'",
            "f'",
            "af'",
            "b'",
            "e''"
        ],
        [
            "e",
            "c'",
            "f'",
            "af'",
            "b'",
            "e''"
        ],
        [
            "e",
            "c'",
            "f'",
            "af'",
            "b'",
            "e''"
        ],

        [
            "e",
            "d'",
            "f'",
            "bf'",
            "b'",
            "e''"
        ],
        [
            "e",
            "d'",
            "f'",
            "bf'",
            "b'",
            "e''"
        ],
        [
            "e",
            "d'",
            "f'",
            "bf'",
            "b'",
            "e''"
        ],
        [
            "e",
            "d'",
            "f'",
            "bf'",
            "b'",
            "e''"
        ],

        [
            "e",
            "c'",
            "f'",
            "af'",
            "b'",
            "e''"
        ],
        [
            "e",
            "c'",
            "f'",
            "af'",
            "b'",
            "e''"
        ],
        [
            "e",
            "c'",
            "f'",
            "af'",
            "b'",
            "e''"
        ],

        [
            "e",
            "ds'",
            "gs'",
            "b'",
            "b'",
            "e''"
        ],
        [
            "e",
            "ds'",
            "gs'",
            "b'",
            "b'",
            "e''"
        ],
        [
            "e",
            "ds'",
            "gs'",
            "b'",
            "b'",
            "e''"
        ],
        [
            "e",
            "ds'",
            "gs'",
            "b'",
            "b'",
            "e''"
        ],
        [
            "e",
            "ds'",
            "gs'",
            "b'",
            "b'",
            "e''"
        ],

        [
            "e",
            "ds'",
            "gs'",
            "b'",
            "b'",
            "e''"
        ],

        [
            "e",
            "c'",
            "f'",
            "af'",
            "b'",
            "e''"
        ],
        [
            "e",
            "c'",
            "f'",
            "af'",
            "b'",
            "e''"
        ],
        [
            "e",
            "c'",
            "f'",
            "af'",
            "b'",
            "e''"
        ],

        [
            "e",
            "d'",
            "f'",
            "bf'",
            "b'",
            "e''"
        ],
        [
            "e",
            "d'",
            "f'",
            "bf'",
            "b'",
            "e''"
        ],
        [
            "e",
            "d'",
            "f'",
            "bf'",
            "b'",
            "e''"
        ],
        [
            "e",
            "d'",
            "f'",
            "bf'",
            "b'",
            "e''"
        ],

        [
            "e",
            "c'",
            "f'",
            "af'",
            "b'",
            "e''"
        ],
        [
            "e",
            "c'",
            "f'",
            "af'",
            "b'",
            "e''"
        ],
    ],
    forget=False,
)
