import evans

pitch_handler_one = evans.PitchHandler(
    pitch_list=[15],
    forget=False,
)

pitch_handler_two = evans.PitchHandler(
    pitch_list=[3],
    forget=False,
)

###
###

flute_pitch_handler_one = evans.PitchHandler(
    pitch_list=[
        "f''",
        "f''",
        "f''",
        "f''",
        "e''",
        "e''",
        "cs''",
        "cs''",
        "c'''",
        "c'''",
        "c'''",
        "c'''",
        "c'''",
        "c'''",
        "fs''",
        "fs''",
        "cs''",
        "cs''",
        "g'",
        "g'",
        "a'",
        "a'",
        "a'",
        "a'",
        "fqs''",
        "fqs''",
        "fs''",
        "fs''",
        "ftqs''",
        "ftqs''",
        "f''",
        "f''",
    ],
    forget=False,
)

guitar_pitch_handler_one = evans.PitchHandler(
    pitch_list=[
        ["e", "c'", "f'", "af'", "b'", "e''"],
        ["e", "c'", "f'", "af'", "b'", "e''"],
        ["e", "c'", "f'", "af'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "c'", "f'", "af'", "b'", "e''"],
        ["e", "c'", "f'", "af'", "b'", "e''"],
        ["e", "c'", "f'", "af'", "b'", "e''"],
        ["e", "ds'", "gs'", "b'", "b'", "e''"],
        ["e", "ds'", "gs'", "b'", "b'", "e''"],
        ["e", "ds'", "gs'", "b'", "b'", "e''"],
        ["e", "ds'", "gs'", "b'", "b'", "e''"],
        ["e", "ds'", "gs'", "b'", "b'", "e''"],
        ["e", "ds'", "gs'", "b'", "b'", "e''"],
        ["e", "c'", "f'", "af'", "b'", "e''"],
        ["e", "c'", "f'", "af'", "b'", "e''"],
        ["e", "c'", "f'", "af'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "c'", "f'", "af'", "b'", "e''"],
        ["e", "c'", "f'", "af'", "b'", "e''"],
    ],
    forget=False,
)

###
###

flute_pitch_handler_two = evans.PitchHandler(
    pitch_list=[
        "a''",
        "aqf''",
        "af''",
        "atqf''",
        "g''",
        "g''",
        "gqs''",
        "gs''",
        "gtqs''",
        "gs''",
        "gqs''",
        "g''",
        "a'",
        "a'",
        "fs'",
        "fs'",
        "cs'",
        "cs'",
        "e'",
        "e'",
        "cs'",
        "cs'",
        "c'",
        "c'",
        "fs'",
        "fs'",
    ],
    forget=False,
)

guitar_pitch_handler_two = evans.PitchHandler(
    pitch_list=[
        "a",
        "a",
        "a",
        "aqf",
        "aqf",
        "aqf",
        "af",
        "af",
        "af",
        "gqs",
        "gqs",
        "gqs",
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "f'", "gs'", "cs'", "b'", "e''"],
        ["e", "f'", "gs'", "cs'", "b'", "e''"],
        ["e", "f'", "gs'", "cs'", "b'", "e''"],
        ["e", "f'", "gs'", "cs'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
    ],
    forget=False,
)

###
###

flute_pitch_handler_three = evans.PitchHandler(
    pitch_list=[
        "f''",
        "gs''",
        "cs''",
        "a'",
        "d'",
        "e'",
        "cs''",
        "c'''",
        "cs'''",
        "a''",
        "f'''",
    ],
    forget=False,
)

guitar_pitch_handler_three = evans.PitchHandler(
    pitch_list=[
        "af",
        "ef'",
        "a''",
        "a''",
        "a''",
        "d''",
        ["e", "cs'", "f'", "g'", "b'", "e''"],
        ["e", "cs'", "f'", "g'", "b'", "e''"],
        ["e", "cs'", "f'", "g'", "b'", "e''"],
        ["e", "cs'", "f'", "g'", "b'", "e''"],
        ["fs'", "d'", "e''"],
        ["cs'", "c''"],
        "a",
        "e'",
        "as''",
        "as''",
        "as''",
        "ds''",
        ["e", "cs'", "f'", "g'", "b'", "e''"],
        ["e", "cs'", "f'", "g'", "b'", "e''"],
        ["e", "cs'", "f'", "g'", "b'", "e''"],
        ["e", "cs'", "f'", "g'", "b'", "e''"],
        ["fs'", "e''"],
        ["cs'", "c''"],
        "c'",
        "g'",
        "a'",
        "ef'",
        "a''",
        "d''",
        "cs'''",
        "g''",
        "cs''",
        "fs'",
        "a",
        ["e", "cs'", "f'", "g'", "b'", "e''"],
        ["af'", "ef'"],
        "d''",
        "cs'''",
        "a''",
        "af''",
        "f''",
        "d''",
        "f'",
        "c'",
        "fs'",
        "e''",
        "g",
        "a",
        "fs'",
        "cs''",
        ["g'", "a'"],
        "fs'",
        "a",
    ],
    forget=False,
)

###
###

flute_pitch_handler_four = evans.PitchHandler(
    pitch_list=[
        "e''",
        "eqs''",
        "f''",
        "fqs''",
        "fs''",
        "ftqs''",
        "g''",
        "gqs''",
        "gs''",
        "gtqs''",
        "a''",
        "aqs''",
        "as''",
        "atqs''",
        "b''",
        "bqs''",
        "c'''",
        "cqs'''",
        "cs'''",
        "ctqs'''",
        "d'''",
    ],
    forget=False,
)

guitar_pitch_handler_four = evans.PitchHandler(
    pitch_list=[
        "e",
        "e",
        "e",
        "e",
        "e",
        "eqf",
        "eqf",
        "eqf",
        "eqf",
        "eqf",
        "ef",
        "ef",
        "ef",
        "ef",
        "ef",
        "etqf",
        "etqf",
        "etqf",
        "etqf",
        "etqf",
        "etqf",
        "etqf",
        "etqf",
    ],
    forget=False,
)

###
###

guitar_pitch_handler_five = evans.PitchHandler(
    pitch_list=[
        "d'",
        "d'",
        "d'",
        "d'",
        "d'",
        "ctqs'",
        "ctqs'",
        "ctqs'",
        "ctqs'",
        "ctqs'",
        "cs'",
        "cs'",
        "cs'",
        "cs'",
        "cs'",
        "cqs'",
        "cqs'",
        "cqs'",
        "cqs'",
        "cqs'",
        "c'",
        "c'",
        "c'",
        "c'",
        "c'",
        "bf",
        "bf",
        "bf",
        "d'",
        "d'",
        "d'",
        "d'",
        "d'",
        "d'",
        "d'",
        "ctqs'",
        "ctqs'",
        "ctqs'",
        "ctqs'",
        "ctqs'",
        "cs'",
        "cs'",
        "cs'",
        "cs'",
        "cs'",
        "cqs'",
        "cqs'",
        "cqs'",
        "cqs'",
        "cqs'",
        "c'",
        "c'",
        "c'",
        "c'",
        "c'",
        "cqs'",
        "cqs'",
        "cqs'",
        "cqs'",
        "cqs'",
    ],
    forget=False,
)

###
###

flute_pitch_handler_six = evans.PitchHandler(
    pitch_list=[
        ["a'", "b'"],
        "gs''",
        "g''",
        "f'",
        "c''",
        "a'",
        ["c''", "d''"],
        "ds'''",
        "f''",
        "gs''",
        "cs''",
        "a'",
        "g'",
        "f''",
        "gs'",
        "d'",
        "as'",
        ["d'", "gs'"],
        ["gs'", "a'"],
        "cs'",
        "as'",
        "gs''",
        "f'''",
        "ds'''",
        "a'''",
        "gs''",
        "b'",
        "fs'",
    ],
    forget=False,
)

guitar_pitch_handler_six = evans.PitchHandler(
    pitch_list=[
        ["f'", "a'"],
        "a'",
        "e''",
        "a'",
        "d'",
        "cs'",
        ["cs'", "d'"],
        "as'",
        "gs''",
        "ds'",
        "f''",
        "cs''",
        "a'",
        ["fs'", "a'"],
        "ds'",
        "d''",
        "d'",
        ["e'", "as'"],
        ["a'", "b'"],
        "ds'''",
        "gs''",
        "gs'",
        "f''",
        "e'''",
        "as'''",
        "d'",
        "a'",
        "g'",
    ],
    forget=False,
)

###
###

flute_pitch_handler_seven = evans.PitchHandler(
    pitch_list=[
        "c'",
        "fs'",
        "e'",
        "cs'",
        "b'",
        "fs''",
        "cs''",
        "g''",
        "cs'''",
        "c'''",
        "fs'''",
        "e'''",
        "g''",
        "a''",
        "fs'",
        "cs'",
        "f'",
        "af'",
        "ef''",
        "d''",
        "a'",
        "cs''",
        "g'",
        "a'",
        "fs'",
    ],
    forget=False,
)

guitar_pitch_handler_seven = evans.PitchHandler(
    pitch_list=[
        "e''",
        "e''",
        "e''",
        "e''",
        "eqf''",
        "eqf''",
        "eqf''",
        "eqf''",
        "ef''",
        "ef''",
        "ef''",
        "ef''",
        "etqf''",
        "etqf''",
        "etqf''",
        "etqf''",
        "b'",
        "b'",
        "b'",
        "bqf'",
        "bqf'",
        "bqf'",
        "bf'",
        "bf'",
        "bf'",
        "btqf'",
        "g'",
        "g'",
        "g'",
        "g'",
        "ftqs'",
        "ftqs'",
        "ftqs'",
        "fs'",
        "fs'",
        "fs'",
        "fs'",
        "fs'",
        "fqs'",
        "fqs'",
        "fqs'",
        "fqs'",
        "fqs'",
        "fqs'",
    ],
    forget=False,
)

###
###

source = evans.PitchSegment([0, 1, 4, 2, 8, 7])
source_ = source + source.transpose(1).invert(3)
source_flute = source_ + source.multiply(1.5).transpose(3).invert().transpose(24)
source_guitar = source_ + source.transpose(3).multiply(2).retrograde()

source_flute += source_flute.transpose(4)
source_guitar += source_guitar.transpose(6).retrograde()

flute_pitch_handler_eight = evans.PitchHandler(
    pitch_list=[_ for _ in source_flute.transpose(12)],
    forget=False,
)

guitar_pitch_handler_eight = evans.PitchHandler(
    pitch_list=[_ for _ in source_guitar],
    forget=False,
)
