import evans

pitch_handler_one = evans.PitchHandler(
    pitch_list=[15],
    forget=False,
)

pitch_handler_two = evans.PitchHandler(
    pitch_list=[3],
    forget=False,
)

###
###

flute_pitch_handler_one = evans.PitchHandler(
    pitch_list=[
        "f''",
        "f''",
        "f''",
        "f''",
        "e''",
        "e''",
        "cs''",
        "cs''",
        "c'''",
        "c'''",
        "c'''",
        "c'''",
        "c'''",
        "c'''",
        "fs''",
        "fs''",
        "cs''",
        "cs''",
        "g'",
        "g'",
        "a'",
        "a'",
        "a'",
        "a'",
        "fqs''",
        "fqs''",
        "fs''",
        "fs''",
        "ftqs''",
        "ftqs''",
        "f''",
        "f''",
    ],
    forget=False,
)

guitar_pitch_handler_one = evans.PitchHandler(
    pitch_list=[
        ["e", "c'", "f'", "af'", "b'", "e''"],
        ["e", "c'", "f'", "af'", "b'", "e''"],
        ["e", "c'", "f'", "af'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "c'", "f'", "af'", "b'", "e''"],
        ["e", "c'", "f'", "af'", "b'", "e''"],
        ["e", "c'", "f'", "af'", "b'", "e''"],
        ["e", "ds'", "gs'", "b'", "b'", "e''"],
        ["e", "ds'", "gs'", "b'", "b'", "e''"],
        ["e", "ds'", "gs'", "b'", "b'", "e''"],
        ["e", "ds'", "gs'", "b'", "b'", "e''"],
        ["e", "ds'", "gs'", "b'", "b'", "e''"],
        ["e", "ds'", "gs'", "b'", "b'", "e''"],
        ["e", "c'", "f'", "af'", "b'", "e''"],
        ["e", "c'", "f'", "af'", "b'", "e''"],
        ["e", "c'", "f'", "af'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "c'", "f'", "af'", "b'", "e''"],
        ["e", "c'", "f'", "af'", "b'", "e''"],
    ],
    forget=False,
)

###
###

flute_pitch_handler_two = evans.PitchHandler(
    pitch_list=[
        "a''",
        "aqf''",
        "af''",
        "atqf''",
        "g''",
        "g''",
        "gqs''",
        "gs''",
        "gtqs''",
        "gs''",
        "gqs''",
        "g''",
        "a'",
        "a'",
        "fs'",
        "fs'",
        "cs'",
        "cs'",
        "e'",
        "e'",
        "cs'",
        "cs'",
        "c'",
        "c'",
        "fs'",
        "fs'",
    ],
    forget=False,
)

guitar_pitch_handler_two = evans.PitchHandler(
    pitch_list=[
        "a",
        "a",
        "a",
        "aqf",
        "aqf",
        "aqf",
        "af",
        "af",
        "af",
        "gqs",
        "gqs",
        "gqs",
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "f'", "gs'", "cs'", "b'", "e''"],
        ["e", "f'", "gs'", "cs'", "b'", "e''"],
        ["e", "f'", "gs'", "cs'", "b'", "e''"],
        ["e", "f'", "gs'", "cs'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
        ["e", "d'", "f'", "bf'", "b'", "e''"],
    ],
    forget=False,
)

###
###

flute_pitch_handler_three = evans.PitchHandler(
    pitch_list=[
        "f''",
        "gs''",
        "cs''",
        "a'",
        "d'",
        "e'",
        "cs''",
        "c'''",
        "cs'''",
        "a''",
        "f'''",
    ],
    forget=False,
)

guitar_pitch_handler_three = evans.PitchHandler(
    pitch_list=[
        "af",
        "ef'",
        "a''",
        "a''",
        "a''",
        "d''",
        ["cs'", "f'"],
        ["cs'", "f'"],
        ["cs'", "f'"],
        ["cs'", "f'"],
        ["fs'", "e''"],
        ["cs'", "c''"],
        "af",
        "ef'",
        "a''",
        "a''",
        "a''",
        "d''",
        ["cs'", "f'"],
        ["cs'", "f'"],
        ["cs'", "f'"],
        ["cs'", "f'"],
        ["fs'", "e''"],
        ["cs'", "c''"],
        "c'",
        "g'",
        "a'",
        "ef'",
        "a''",
        "d''",
        "cs'''",
        "g''",
        "cs''",
        "fs'",
        "a",
        ["cs'", "f'"],
        ["af'", "ef'"],
        "d''",
        "cs'''",
        "a''",
        "af''",
        "f''",
        "d''",
        "f'",
        "c'",
        "fs'",
        "e''",
        "g",
        "a",
        "fs'",
        "cs''",
        ["g'", "a'"],
        "fs'",
        "a",
    ],
    forget=False,
)

###
###

flute_pitch_handler_four = evans.PitchHandler(
    pitch_list=[
        "e''",
        "eqs''",
        "f''",
        "fqs''",
        "fs''",
        "ftqs''",
        "g''",
        "gqs''",
        "gs''",
        "gtqs''",
        "a''",
        "aqs''",
        "as''",
        "atqs''",
        "b''",
        "bqs''",
        "c'''",
        "cqs'''",
        "cs'''",
        "ctqs'''",
        "d'''",
    ],
    forget=False,
)

guitar_pitch_handler_four = evans.PitchHandler(
    pitch_list=[
        "e",
        "e",
        "e",
        "e",
        "e",
        "eqf",
        "eqf",
        "eqf",
        "eqf",
        "eqf",
        "ef",
        "ef",
        "ef",
        "ef",
        "ef",
        "etqf",
        "etqf",
        "etqf",
        "etqf",
        "etqf",
        "etqf",
        "etqf",
        "etqf",
    ],
    forget=False,
)
